<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ide dan Inspirasi_image-secondary</name>
   <tag></tag>
   <elementGuidId>040554ea-afbf-4a14-bea0-1265a6924176</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#image-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='Informa Bally Meja Setrika Dengan Keranjang Laundry'])[2]/parent::a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2ff548f6-a684-4854-9237-f88bcdbc6776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shim</value>
      <webElementGuid>ff5a9f66-d1db-4a5b-870d-2d5cade17f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>image-secondary</value>
      <webElementGuid>027e4982-848d-47a9-a222-bca8fb2bc7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Informa Bally Meja Setrika Dengan Keranjang Laundry</value>
      <webElementGuid>c50d28c6-92b5-4c2e-b7d4-a734fe470036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Informa Bally Meja Setrika Dengan Keranjang Laundry</value>
      <webElementGuid>037afc78-06ed-41e2-8ff3-246daaeaeb79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>170</value>
      <webElementGuid>e377e09b-676c-4092-8082-340b470006da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>170</value>
      <webElementGuid>3c5d85bd-b961-47ef-899e-ae582f5f4621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://res.cloudinary.com/ruparupa-com/image/upload/w_300,h_300,f_auto,q_auto/f_auto,q_auto/v1668057864/Products/10487386_2.jpg</value>
      <webElementGuid>31789d35-0bff-4968-81b6-fb2ab2e08d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-category-list&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-8 right-content&quot;]/div[@class=&quot;product-container-pcp container-card&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-3&quot;]/div[@class=&quot;product-container product-container-hovered&quot;]/div[@class=&quot;image-card&quot;]/div[@class=&quot;bitmap&quot;]/div[@class=&quot;item selected&quot;]/span[1]/a[1]/img[@id=&quot;image-secondary&quot;]</value>
      <webElementGuid>8f37f870-cc6b-41e8-a156-a6d85695d081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='image-secondary']</value>
      <webElementGuid>88629ec8-1d0c-430c-8177-a6a99cdde6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='product-category-list']/div/div[2]/div[2]/div/div/div/div/div/div/span/a/img[2]</value>
      <webElementGuid>c44a4a0a-fb87-4de2-9d8d-3c919acfa176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Informa Bally Meja Setrika Dengan Keranjang Laundry'])[2]/parent::a</value>
      <webElementGuid>5fd1b468-ea58-4dbf-94f3-f1edce5a50b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img[2]</value>
      <webElementGuid>54b0e19e-48fb-4485-a1ea-5a61b0ea9b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'image-secondary' and @title = 'Informa Bally Meja Setrika Dengan Keranjang Laundry' and @alt = 'Informa Bally Meja Setrika Dengan Keranjang Laundry' and @src = 'https://res.cloudinary.com/ruparupa-com/image/upload/w_300,h_300,f_auto,q_auto/f_auto,q_auto/v1668057864/Products/10487386_2.jpg']</value>
      <webElementGuid>d681aeef-a27f-4a6e-bb4d-af98a93b32d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
