<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Daftar_email-login</name>
   <tag></tag>
   <elementGuidId>33c70b56-53a1-4d93-ad67-27500affce64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email-login&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email-login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f71614b1-0d86-4330-afc8-4fc772e2b199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29b5e05e-5ba6-4366-9534-79a8baa2dcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email-login</value>
      <webElementGuid>706c4288-d2e6-4046-b48b-8e93ffebae90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Alamat email atau nomor telepon</value>
      <webElementGuid>6fb81817-c335-49b7-8153-9bb4226e8f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>948f8fc8-496d-4722-b8f2-119b148a5ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7b3e5f90-03c6-48d6-a11d-b77c9a6848c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/form[1]/div[1]/div[@class=&quot;form-icon&quot;]/input[1]</value>
      <webElementGuid>6d586d02-ea4d-4fa8-bd8e-f235d23c7264</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email-login']</value>
      <webElementGuid>ed64d630-ff13-4442-b54e-21d8f6e54659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/form/div/div/input</value>
      <webElementGuid>e81a9b4a-6a37-4800-ad0e-8c2d9ec4ccd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>40438ac4-e8ab-4519-8469-a9e0db5416b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email-login' and @placeholder = 'Alamat email atau nomor telepon']</value>
      <webElementGuid>4ae13302-9242-4e26-890e-3eed82095669</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
