<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>34887fdc-825c-420a-9d68-ce1b56de9ea3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submit-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submit-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b1c5212d-d653-4df0-96a5-4a2e23d649ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d88845e8-4468-48e2-9073-f98b16b4280f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-btn</value>
      <webElementGuid>604f6e34-843b-412f-9299-3c6b4efd2e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-full btn-primary btn-m</value>
      <webElementGuid>d4864e08-7d64-4b5e-a743-70d8b0112edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>08c01a65-a1f9-4b82-895b-219a6c133e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-btn&quot;)</value>
      <webElementGuid>534dddca-5644-4034-9011-4e5e7d041ecb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submit-btn']</value>
      <webElementGuid>be062c91-68e4-438e-93ec-4919b8d11bcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
