<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Alamat email atau nomor telepon tidak valid</name>
   <tag></tag>
   <elementGuidId>2b54c51e-8e5a-4ef5-bf74-1ce627a1fcdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailContentWarning</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='emailContentWarning']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7dfef2c1-6c8b-40b5-80d7-fa1579a31ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-content-warning</value>
      <webElementGuid>db3c430a-1d6b-4baa-9850-86a6c1d8ae99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailContentWarning</value>
      <webElementGuid>d757bd94-d552-43a4-b1e9-e2e32e2c21a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alamat email atau nomor telepon tidak valid</value>
      <webElementGuid>0faccccc-5a2d-46e8-8737-540361e608be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailContentWarning&quot;)</value>
      <webElementGuid>91f9a255-65f9-47bf-9696-5de878dd7402</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='emailContentWarning']</value>
      <webElementGuid>d7543cc7-f888-4dc4-a261-438deb8b33c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='emailValidation']/div</value>
      <webElementGuid>1df156b9-a6d4-412d-a4e9-3161f6267285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::div[5]</value>
      <webElementGuid>64b5d6c7-320b-49b0-ac61-9299634f5b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/following::div[5]</value>
      <webElementGuid>0b5e336c-50cf-423a-b9fd-308be0ff48bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata sandi minimal 5 karakter'])[1]/preceding::div[1]</value>
      <webElementGuid>a2b7a594-8318-4163-b6af-37ebc5df1b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa kata sandi?'])[1]/preceding::div[3]</value>
      <webElementGuid>d9093320-884b-4605-9687-8c01573687a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alamat email atau nomor telepon tidak valid']/parent::*</value>
      <webElementGuid>569b3f39-3a22-4a81-b86f-7b5035b5f919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/form/div/div</value>
      <webElementGuid>9003a52a-c4c8-40ef-bbaa-00a5335d4f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'emailContentWarning' and (text() = 'Alamat email atau nomor telepon tidak valid' or . = 'Alamat email atau nomor telepon tidak valid')]</value>
      <webElementGuid>a80ec185-4cd9-4af1-aedc-30730dba0536</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
