<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kata sandi minimal 5 karakter</name>
   <tag></tag>
   <elementGuidId>a9667e6e-e961-4f61-a873-f63599b806eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passwordContentWarning</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='passwordContentWarning']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5460e353-ec24-467d-9395-76d348092c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-content-warning</value>
      <webElementGuid>e3472048-b6de-424d-aa81-a0bce8857958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwordContentWarning</value>
      <webElementGuid>511d9977-08e3-49b2-9655-4218d52dea67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kata sandi minimal 5 karakter </value>
      <webElementGuid>467a630e-5491-4501-bf9b-c611c68c71f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordContentWarning&quot;)</value>
      <webElementGuid>d995bdee-50b4-4a7f-927d-79069df96ddd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='passwordContentWarning']</value>
      <webElementGuid>5baa95f9-627e-40c9-9d67-ffe33ec317b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passwordValidation']/div</value>
      <webElementGuid>ae13de6e-5131-400a-a2eb-86b537ed6066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat email atau nomor telepon tidak valid'])[1]/following::div[2]</value>
      <webElementGuid>0271147f-020b-40b8-9a14-86ab38ab55c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::div[7]</value>
      <webElementGuid>a07c7f37-57d8-43c0-b530-45feac21e857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa kata sandi?'])[1]/preceding::div[1]</value>
      <webElementGuid>7bcb065b-3020-4bef-a933-92855b3c7732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maaf, ada kesalahan penulisan pada informasi Anda'])[1]/preceding::div[1]</value>
      <webElementGuid>d1aa1433-1c11-4908-a2d9-622fa668b8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kata sandi minimal 5 karakter']/parent::*</value>
      <webElementGuid>3bf055ee-dd34-47b9-9f6d-8c0ce1c35f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/form/div[2]/div</value>
      <webElementGuid>f145efa6-1a90-4e71-9940-b06b16ae3d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'passwordContentWarning' and (text() = 'Kata sandi minimal 5 karakter ' or . = 'Kata sandi minimal 5 karakter ')]</value>
      <webElementGuid>b462754d-6763-45ff-8116-40ce23606b0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
