<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Maaf, ada kesalahan penulisan pada informasi Anda</name>
   <tag></tag>
   <elementGuidId>cc8a18c4-fa65-4766-8a06-cea0f576b6f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-error-alert</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-error-alert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f96f143c-3f27-4a50-b9fa-e4c7ff732b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-error-alert</value>
      <webElementGuid>7e2752ba-e0fb-4d75-ac4b-5353ba6d3838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order-danger-alert no-margin-bottom mt15 mb10</value>
      <webElementGuid>e1563deb-6950-459e-a25f-c52d396afad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Maaf, ada kesalahan penulisan pada informasi Anda</value>
      <webElementGuid>152bad9d-d33a-4447-b29f-2f2e8d9bfdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-error-alert&quot;)</value>
      <webElementGuid>fefaea6a-c697-4154-92e0-466f5f269923</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='login-error-alert']</value>
      <webElementGuid>db95460f-d5c4-4e41-8673-6c136ff8415b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/div/form/div[3]</value>
      <webElementGuid>5768a813-7792-494e-9d86-cffad8ec1fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa kata sandi?'])[1]/following::div[1]</value>
      <webElementGuid>40ec595b-d656-44f7-966c-eb313d86481b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata sandi minimal 5 karakter'])[1]/following::div[1]</value>
      <webElementGuid>ae8fb495-4121-4038-8002-3ec60d0f3e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/preceding::div[1]</value>
      <webElementGuid>62fda33c-3cb9-4f6a-b7b5-397cccd77c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atau'])[1]/preceding::div[1]</value>
      <webElementGuid>9cf6e41c-b527-4e49-889c-812078ef3326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Maaf, ada kesalahan penulisan pada informasi Anda']/parent::*</value>
      <webElementGuid>a2429d3a-605a-4947-8e22-6bf7dd7d0d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]</value>
      <webElementGuid>cec1f4f1-933d-4593-aa54-68b6ae92c4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'login-error-alert' and (text() = ' Maaf, ada kesalahan penulisan pada informasi Anda' or . = ' Maaf, ada kesalahan penulisan pada informasi Anda')]</value>
      <webElementGuid>bf19f517-4585-4ddd-aca1-d2e026f06d5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
