<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6c4d9b85-1922-4644-9dad-864ad9ac7508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[7]/section/div/div[3]/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>71a21d77-3076-456d-83cb-6862c2014ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>289px</value>
      <webElementGuid>24ea5a92-cc73-4582-8f8a-901d9bbf46cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>162px</value>
      <webElementGuid>348f0842-c7e6-4618-995c-e558d6d1fc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.ruparupa.io/filters:format(webp)/promotion/ruparupa/hot-offers/07-22/bogo/miniblock-produk-terbaru.png</value>
      <webElementGuid>1d733cb1-405a-4499-9e51-c4c8a02c25ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[7]/section[@class=&quot;explore margin-top-s margin-bottom-s container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;explore-by-category-4grid&quot;]/div[@class=&quot;explore-item&quot;]/div[@class=&quot;bitmap&quot;]/a[1]/div[@class=&quot;lazyload-wrapper&quot;]/img[1]</value>
      <webElementGuid>31b4b862-ec81-43d3-b070-28325687e22b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[7]/section/div/div[3]/div/div/a/div/img</value>
      <webElementGuid>f0423310-e60c-4916-9056-bebdd499404b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn.ruparupa.io/filters:format(webp)/promotion/ruparupa/hot-offers/07-22/bogo/miniblock-produk-terbaru.png')]</value>
      <webElementGuid>5bbaa352-8b94-496d-86f9-ad09c1773f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/div/img</value>
      <webElementGuid>33070451-588a-45f6-b186-24f72469cd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.ruparupa.io/filters:format(webp)/promotion/ruparupa/hot-offers/07-22/bogo/miniblock-produk-terbaru.png']</value>
      <webElementGuid>d3d0badb-cdc9-457f-96d5-d51da11514bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
