<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>97f1306e-f036-435d-92c7-ce966cd5a055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='product-category-list']/section/div[2]/div[3]/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c7ed35cd-a14c-4819-bae0-94e4ffee61a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>289px</value>
      <webElementGuid>04f1c67f-a533-4008-9527-f75b75379fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>162px</value>
      <webElementGuid>6cd43077-393b-47d7-bf3e-a4da410159ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.ruparupa.io/filters:format(webp)/promotion/ruparupa/payday-nov-22/footer/bogo.png</value>
      <webElementGuid>a2dde840-ea3f-4db7-8518-bee3d99c0f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-category-list&quot;)/section[@class=&quot;explore margin-top-s margin-bottom-s container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;explore-by-category-3grid&quot;]/div[@class=&quot;explore-item&quot;]/div[@class=&quot;bitmap&quot;]/a[1]/div[@class=&quot;lazyload-wrapper&quot;]/img[1]</value>
      <webElementGuid>bec1dccc-1e61-488a-8a4a-2a8941887a85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='product-category-list']/section/div[2]/div[3]/div/div/a/div/img</value>
      <webElementGuid>0019a186-993d-41f3-b4a5-d37a2540e12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn.ruparupa.io/filters:format(webp)/promotion/ruparupa/payday-nov-22/footer/bogo.png')]</value>
      <webElementGuid>38918819-5669-4e4f-b911-ed6387c9c1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/a/div/img</value>
      <webElementGuid>7d7e41c8-3c7a-4bed-857b-ba94244fe9f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.ruparupa.io/filters:format(webp)/promotion/ruparupa/payday-nov-22/footer/bogo.png']</value>
      <webElementGuid>2f3dfce8-b601-439b-89f5-39e54d2f0d3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
